[project]
name = "syn-data-gen-visual-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "opencv-python-headless>=4.12.0.88",
    "streamlit>=1.47.1",
    "ultralytics>=8.3.174",
]
