apiVersion: apps/v1
kind: Deployment
metadata:
  name: object-detection-deployment
  labels:
    app: object-detection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: object-detection
  template:
    metadata:
      labels:
        app: object-detection
    spec:
      containers:
      - name: object-detection-container
        image: registry.cn-hangzhou.aliyuncs.com/99cloud-sh/object_detection
        ports:
        - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: object-detection-service
spec:
  type: NodePort
  selector:
    app: object-detection
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30188
